matrix:
  include:
    - language: ruby
      stage: test
      install: gem install rspec
      before_script:
        - cd app/test
      script:
        - bundle exec rspec

    - language: c
      stage: test
      before_script:
        - cd infra/terraform/
      script:
        - make

    - language: C
      stage: package
      before_script:
        - cd app/
      script:
        - make
