matrix:
  include:
    - language: ruby
      stage: test
      before_script:
        - cd app/test
      script:
        - bundle exec rspec

    - language: C
      stage: test
      before_script:
        - cd infra/
      script:
        - make

    - language: C
      stage: deploy
      script:
        - make
